# Model Mapping Configuration
# Simple names -> Actual API IDs
# Use simple names in agents.yaml, they get mapped to real IDs automatically

models:
  # ============================================================
  # ANTHROPIC MODELS (Cheapest to Most Expensive)
  # ============================================================
  
  # HAIKU Models (CHEAPEST - Best for Testing)
  haiku-3:
    id: "claude-3-haiku-20240307"
    provider: "anthropic"
    pricing:
      input_mtok: 0.25   # $0.25 per 1M input tokens
      output_mtok: 1.25  # $1.25 per 1M output tokens
    notes: "Legacy Haiku 3 - CHEAPEST option, great for simple tasks"
    
  haiku-3.5:
    id: "claude-3-5-haiku-20241022"
    provider: "anthropic"
    pricing:
      input_mtok: 0.80   # $0.80 per 1M input tokens
      output_mtok: 4.00  # $4.00 per 1M output tokens
    notes: "Legacy Haiku 3.5 - Faster & smarter than 3, still very cheap"
  
  haiku-4.5:
    id: "claude-haiku-4-5-20251001"
    provider: "anthropic"
    pricing:
      input_mtok: 1.00   # $1 per 1M input tokens
      output_mtok: 5.00  # $5 per 1M output tokens
    notes: "Latest Haiku 4.5 - Best speed/intelligence balance for cheap"
  
  # SONNET Models (Mid-tier - Use sparingly)
  sonnet-3.7:
    id: "claude-3-7-sonnet-20250219"
    provider: "anthropic"
    pricing:
      input_mtok: 3.00   # $3 per 1M input tokens
      output_mtok: 15.00 # $15 per 1M output tokens
    notes: "Legacy Sonnet 3.7 - Good reasoning, 4x more expensive than Haiku 3.5"
  
  sonnet-4:
    id: "claude-sonnet-4-20250514"
    provider: "anthropic"
    pricing:
      input_mtok: 3.00
      output_mtok: 15.00
    notes: "Sonnet 4 - Better reasoning than 3.7, same price"
  
  sonnet-4.5:
    id: "claude-sonnet-4-5-20250929"
    provider: "anthropic"
    pricing:
      input_mtok: 3.00
      output_mtok: 15.00
    notes: "Latest Sonnet 4.5 - Best for complex coding/agentic tasks"
  
  # OPUS Models (Expensive - Use ONLY for critical decisions)
  opus-4.1:
    id: "claude-opus-4-1-20250805"
    provider: "anthropic"
    pricing:
      input_mtok: 15.00  # $15 per 1M input tokens
      output_mtok: 75.00 # $75 per 1M output tokens
    notes: "Opus 4.1 - Most expensive, use ONLY for specialized reasoning"
  
  # ============================================================
  # OPENAI MODELS (Alternative provider)
  # ============================================================
  
  gpt-4o:
    id: "gpt-4o"
    provider: "openai"
    pricing:
      input_mtok: 2.50   # $2.50 per 1M input tokens
      output_mtok: 10.00 # $10 per 1M output tokens
    notes: "OpenAI's flagship - Similar to Sonnet 4 pricing"

# ============================================================
# RECOMMENDED USAGE FOR $50/month BUDGET
# ============================================================
# 
# Testing & Development:
#   - Use: haiku-3 or haiku-3.5 (cheapest)
#   - Cost: ~$0.001-0.004 per agent run
#   - Budget: Can do 10,000-50,000 runs/month
#
# Production (Light reasoning):
#   - Use: haiku-3.5 or haiku-4.5
#   - Cost: ~$0.004-0.010 per agent run
#   - Budget: Can do 5,000-12,000 runs/month
#
# Production (Complex reasoning):
#   - Use: sonnet-3.7 or sonnet-4.5 (sparingly!)
#   - Cost: ~$0.020-0.050 per agent run
#   - Budget: Can do 1,000-2,500 runs/month
#
# Critical decisions only:
#   - Use: opus-4.1 (RARELY!)
#   - Cost: ~$0.100-0.300 per agent run
#   - Budget: Can do 150-500 runs/month
#
# STRATEGY:
# - Use haiku-3.5 for 90% of turns (data gathering, simple analysis)
# - Use sonnet-4.5 for 10% of turns (complex reasoning, validation)
# - NEVER use Opus in scheduled agents (only manual deep dives)
# ============================================================

# Deprecated models (DO NOT USE - will be retired)
deprecated:
  - "claude-3-5-sonnet-20240620"   # Retired
  - "claude-3-5-sonnet-20241022"   # Retired Oct 2025
  - "claude-2"                      # Retired
  - "claude-2.1"                    # Retired

