services:
  satbase-api:
    build: .
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./libs/satbase_core/config:/app/libs/satbase_core/config:ro
      - ./apps:/app/apps:ro
      - ./libs:/app/libs:ro
    command: ["uvicorn", "apps.satbase_api.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]

  satbase-ingest:
    build: .
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./libs/satbase_core/config:/app/libs/satbase_core/config:ro
    command: ["python", "-m", "libs.satbase_core.ingest.run_daily"]

  looking-glass:
    build: ./apps/looking_glass
    network_mode: host
    environment:
      - VITE_API_BASE=http://127.0.0.1:8080
    working_dir: /app
    volumes:
      - ./apps/looking_glass/src:/app/src:ro

