import { c as create_ssr_component, d as add_attribute } from "../../../../chunks/ssr.js";
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let correlationSymbols = "";
  let correlationWindow = 90;
  return `<div class="max-w-4xl mx-auto p-6"><h1 class="text-3xl font-bold text-neutral-100 mb-6" data-svelte-h="svelte-p8ojb0">Learn: Background Analytics</h1>  <div class="mb-8 bg-neutral-900 rounded border border-neutral-800 p-6"><h2 class="text-xl font-semibold text-neutral-200 mb-4" data-svelte-h="svelte-1blji0o">Correlation Analysis</h2> <p class="text-sm text-neutral-400 mb-4" data-svelte-h="svelte-9hc7ho">Compute price correlations between symbols and store as CORRELATES_WITH edges.</p> <div class="space-y-3"><div><label class="block text-sm font-medium text-neutral-300 mb-1" data-svelte-h="svelte-1hlwcpy">Symbols (comma-separated)</label> <input type="text" placeholder="e.g., NVDA, AMD, INTC" class="w-full px-3 py-2 bg-neutral-950 border border-neutral-700 rounded text-neutral-100 focus:outline-none focus:border-indigo-500"${add_attribute("value", correlationSymbols, 0)}></div> <div class="grid grid-cols-2 gap-3"><div><label class="block text-sm font-medium text-neutral-300 mb-1" data-svelte-h="svelte-bpuord">Window (days)</label> <input type="number" min="30" max="365" class="w-full px-3 py-2 bg-neutral-950 border border-neutral-700 rounded text-neutral-100 focus:outline-none focus:border-indigo-500"${add_attribute("value", correlationWindow, 0)}></div> <div><label class="block text-sm font-medium text-neutral-300 mb-1" data-svelte-h="svelte-14znm5s">Method</label> <select class="w-full px-3 py-2 bg-neutral-950 border border-neutral-700 rounded text-neutral-100 focus:outline-none focus:border-indigo-500"><option value="spearman" data-svelte-h="svelte-109fbfi">Spearman</option><option value="pearson" data-svelte-h="svelte-482t66">Pearson</option></select></div></div> <button class="px-4 py-2 rounded bg-indigo-600 hover:bg-indigo-500 text-white" data-svelte-h="svelte-t9dnrx">Start Correlation Analysis</button> ${``}</div></div>  <div class="bg-neutral-900 rounded border border-neutral-800 p-6"><h2 class="text-xl font-semibold text-neutral-200 mb-4" data-svelte-h="svelte-1ks2mr8">Community Detection</h2> <p class="text-sm text-neutral-400 mb-4" data-svelte-h="svelte-uojr4t">Run Louvain community detection on the company graph using Neo4j GDS.</p> <button class="px-4 py-2 rounded bg-indigo-600 hover:bg-indigo-500 text-white" data-svelte-h="svelte-1ftz9v8">Start Community Detection</button> ${``}</div></div>`;
});
export {
  Page as default
};
