# Shared Turn Templates (YAML Anchors for reusability)
_analyst_turns: &analyst_turns
  - id: 1
    name: "load_watchlist"
    model: "haiku-3.5"
    max_tokens: 1500
    mcps: ["satbase"]
    prompt: "Load your watchlist from Satbase to see which tickers you should analyze today."

  - id: 2
    name: "gather_data"
    model: "haiku-3.5"
    max_tokens: 2000
    mcps: ["satbase"]
    prompt: "Gather news, prices, and macro data for your tickers from the last 48 hours."

  - id: 3
    name: "semantic_search"
    model: "haiku-3.5"
    max_tokens: 2000
    mcps: ["tesseract"]
    prompt: "Use semantic search to find articles related to supply chain, demand changes, and regulatory shifts."

  - id: 4
    name: "analyze_causal"
    model: "haiku-3.5"
    max_tokens: 3000
    prompt: "Analyze the causal chains: Why are prices moving? What are the mechanisms?"

  - id: 5
    name: "link_and_hypothesize"
    model: "haiku-3.5"
    max_tokens: 2000
    mcps: ["manifold", "ariadne"]
    prompt: "Search for existing thoughts. Formulate hypotheses about what's happening."

  - id: 6
    name: "store_insights"
    model: "haiku-3.5"
    max_tokens: 1500
    mcps: ["manifold", "ariadne"]
    prompt: "Store your signals as Thoughts and your hypotheses in Ariadne."

orchestrator:
  timezone: "UTC"

budget:
  daily_tokens: 101000
  monthly_budget_usd: 50

mcps:
  satbase:
    command: "node"
    args: ["../mcps/satbase/dist/index-stdio.js"]
  tesseract:
    command: "node"
    args: ["../mcps/tesseract/dist/index-stdio.js"]
  manifold:
    command: "node"
    args: ["../mcps/manifold/dist/index-stdio.js"]
  ariadne:
    command: "node"
    args: ["../mcps/ariadne/dist/index-stdio.js"]

agents:
  discovery:
    enabled: false
    schedule: "*/2 * * * * *"
    model: "haiku-3.5"
    budget_daily_tokens: 5000
    timeout_minutes: 3
    rules_file: "./agent-rules/discovery.md"
    turns:
      - id: 1
        name: "load_watchlist"
        max_tokens: 1000
        mcps: ["satbase"]
        prompt: "Load your watchlist to see which sectors and themes are in scope today."

      - id: 2
        name: "get_trends"
        max_tokens: 2000
        mcps: ["satbase"]
        prompt: "Get trending tickers and news heatmap. What are the top 5 themes/events today?"

      - id: 3
        name: "create_signals"
        max_tokens: 1500
        mcps: ["manifold"]
        prompt: "Create Signal thoughts for the top 5 discoveries with confidence scores."

  analyst_tech:
    enabled: false
    schedule: "*/5 * * * * *"
    batch: 1
    sector: "tech"
    model: "haiku-3.5"
    budget_daily_tokens: 12000
    timeout_minutes: 8
    rules_file: "./agent-rules/analyst-tech.md"
    turns: *analyst_turns

  analyst_biotech:
    enabled: false
    schedule: "*/5 * * * * *"
    batch: 1
    sector: "biotech"
    model: "haiku-3.5"
    budget_daily_tokens: 12000
    timeout_minutes: 8
    rules_file: "./agent-rules/analyst-biotech.md"
    turns: *analyst_turns

  analyst_commodities:
    enabled: false
    schedule: "*/5 * * * * *"
    batch: 1
    sector: "commodities"
    model: "haiku-3.5"
    budget_daily_tokens: 12000
    timeout_minutes: 8
    rules_file: "./agent-rules/analyst-commodities.md"
    turns: *analyst_turns

  analyst_macro:
    enabled: false
    schedule: "*/5 * * * * *"
    batch: 2
    sector: "macro"
    model: "haiku-3.5"
    budget_daily_tokens: 12000
    timeout_minutes: 8
    rules_file: "./agent-rules/analyst-macro.md"
    turns: *analyst_turns

  analyst_geopolitics:
    enabled: false
    schedule: "*/5 * * * * *"
    batch: 2
    sector: "geopolitics"
    model: "haiku-3.5"
    budget_daily_tokens: 12000
    timeout_minutes: 8
    rules_file: "./agent-rules/analyst-geopolitics.md"
    turns: *analyst_turns

  validator:
    enabled: false
    schedule: "*/10 * * * * *"
    model: "haiku-3.5"
    budget_daily_tokens: 12000
    timeout_minutes: 8
    rules_file: "./agent-rules/validator.md"
    turns:
      - id: 1
        name: "load_hypotheses"
        model: "haiku-3.5"
        max_tokens: 1500
        mcps: ["ariadne"]
        prompt: "Load all pending hypotheses from Ariadne that need evidence collection."

      - id: 2
        name: "gather_evidence"
        model: "haiku-3.5"
        max_tokens: 2000
        mcps: ["satbase", "tesseract", "manifold"]
        prompt: "Gather evidence for each hypothesis: news, prices, related thoughts."

      - id: 3
        name: "validate"
        model: "haiku-3.5"
        max_tokens: 3000
        prompt: "Evaluate each hypothesis: Is it supported or contradicted? Confidence?"

      - id: 4
        name: "store_evidence"
        model: "haiku-3.5"
        max_tokens: 1500
        mcps: ["ariadne"]
        prompt: "Store evidence and validation decisions in Ariadne."

  trader:
    enabled: false
    schedule: "*/15 * * * * *"
    model: "haiku-3.5"
    budget_daily_tokens: 12000
    timeout_minutes: 10
    rules_file: "./agent-rules/trader.md"
    turns:
      - id: 1
        name: "load_patterns"
        model: "haiku-3.5"
        max_tokens: 1500
        mcps: ["ariadne"]
        prompt: "Load validated patterns (confidence >= 0.8) and current market regimes."

      - id: 2
        name: "calculate_impact"
        model: "haiku-3.5"
        max_tokens: 2000
        mcps: ["ariadne", "satbase"]
        prompt: "For each pattern: calculate impact on top 5 entities, get current prices."

      - id: 3
        name: "evaluate"
        model: "haiku-3.5"
        max_tokens: 3000
        mcps: ["manifold"]
        prompt: "Evaluate trade feasibility: What's the risk/reward? Are there related risks?"

      - id: 4
        name: "formulate"
        model: "haiku-3.5"
        max_tokens: 2000
        prompt: "Formulate trade ideas with entry, stop loss, take profit, and thesis."

      - id: 5
        name: "store"
        model: "haiku-3.5"
        max_tokens: 1500
        mcps: ["manifold", "ariadne"]
        prompt: "Store trade ideas as Thoughts and link to underlying patterns/hypotheses."

  reflection:
    enabled: false
    schedule: "0 23 * * 0"
    model: "haiku-3.5"
    budget_daily_tokens: 8000
    timeout_minutes: 6
    rules_file: "./agent-rules/reflection.md"
    turns:
      - id: 1
        name: "load_trades"
        max_tokens: 2000
        mcps: ["manifold"]
        prompt: "Load all trade ideas from the past week."

      - id: 2
        name: "evaluate_accuracy"
        model: "haiku-3.5"
        max_tokens: 3000
        prompt: "Evaluate: Were the hypotheses correct? What was the accuracy?"

      - id: 3
        name: "store_learnings"
        max_tokens: 1500
        mcps: ["manifold"]
        prompt: "Store learnings as Reflection thoughts for next week."
