# Agent Rules Library
rules:
  - id: rule_example_001
    name: "Example Rule"
    content: |
      # This is an example rule
      Use this as a template for creating new rules.
    description: "Template rule for reference"
    created_at: "2025-10-25 21:00:00"
    updated_at: "2025-10-25 21:00:00"
